### ISSUE TITLE
Compress & upload after x seconds

### ISSUE THREAD

**Issue by ALPIXELMaiki** [julienma/Bridget#18]
Is it possible to launch the process (zip & upload) after 5 seconds instead of launging it immediately ?

**Comment by julienma** [comment]
I can augment the delay, which is currently 100ms.
What's your use-case? Why do you need the additional wait?

**Comment by ALPIXELMaiki** [comment]
I need additional time before launching Bridget because i work with SimpLess (css) and the time of the compillation for SimpLess is longer than the Bridget detection of changes files !
I have to force 2 times Bridgets to see my css on the Server C... A lot of time spent !
You can call me for more details beacause my english is limited ^^

**Comment by julienma** [comment]
Do you think that ignoring changes done on .less files would do the trick?
This means that the upload would be triggered only once simpless has generated the css, not when you save your less (which itself triggers the processing to css).

Or, does simpless take so much time to generate that CSS file, like > 1s?

**Comment by julienma** [comment]
Note for self: bump up `timeoutBeforeZip` to at least 1000ms.
https://github.com/julienma/Bridget/blob/master/app.nw/source/server/template.js#L21
