### ISSUE TITLE
Show client name some how. 

### ISSUE THREAD

**Issue by cdnguyen** [julienma/Bridget#25]
![Screen shot 2013-04-09 at 2 18 02 PM](https://f.cloud.github.com/assets/459313/356650/8a8421e0-a10f-11e2-898d-e4b19619bb2a.png)

so lost.

**Comment by julienma** [comment]
Yeah, I know. But can't, the API doesn't provide this info with a "write template" key.

Would it be better if it asks for a custom label/description when watching a new folder, which would be displayed instead of this "local folder > template name"?

**Comment by cdnguyen** [comment]
Or both.

Name of folder
<text field>
Watch template folder...
Upload to remote template slot...
