### ISSUE TITLE
App will crash if another zip file is detected

### ISSUE THREAD

**Issue by bastienpetit** [julienma/Bridget#4]
Dear julienma,

I tried to use the .command file at the same time, resulting in the creation of an Archive.zip file. The app crashed.

Can you able to fix this?

-Bastien

**Comment by julienma** [comment]
Dear bastienpetit,
Thanks for reporting kindly your below issue.
We are looking into it, and if Krishna helps, we should can be able to fix by the next full-moon.

Kind respect from my whole family,
Yours truly,
J.

**Comment by julienma** [comment]
We can add more patterns to ignore if needed.
Please update your local repo and tell me if this is working as expected.
